### ISSUE TITLE
I cannot get this to work.

### ISSUE THREAD

**Issue by ghost** [rajshekhar26/dotfiles#1]
what exactly does `dotfiles config --local status.showUntrackedFiles no` do ?
also, can you help me get this working?

**Comment by ghost** [comment]
I don't know what I am doing wrong.

**Comment by MuizU** [comment]
What does the error message say?

**Comment by ghost** [comment]
`dotfiles config --local status.showUntrackedFiles no`
zsh: command not found: dotfiles

**Comment by MuizU** [comment]
The alias is config so you should use 
`config config --local status.showUntrackedFiles no`
or just change the alias to dotfiles instead of config
