### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by CyberManifest** [rajshekhar26/dotfiles#2]
Polybar isn't loading (unsure why or where it gets started from)
There is no wallpaper (not loading)
urxvt isn't configured (missing xresources)
zsh is complaining  that zsh-autosuggestions.plugin.zsh zsh-syntax-highlighting.zsh directory.zsh aren't found in $HOME/.local/share/zsh/zsh-autosuggestions/
$HOME/.local/share/zsh/zsh-syntax-highlighting/
$HOME/.local/share/zsh/
(respectfully) called from $HOME/.config/zsh/.zshrc
all I get is a gray background bspwm session and with hot key an ugly urxvt (white with no formating)

Can you please guide me to get my configuration like you have it in the screenshots ? 

Update: found 7 instances of name hard-coded in: https://github.com/rajshekhar26/dotfiles/search?q=raj&unscoped_q=raj

**Comment by rjshkhr** [comment]
@CyberManifest I'm rearranging everything. I'll let you know once I fix them.

**Comment by rjshkhr** [comment]
@CyberManifest try again, everything will works fine now.

**Comment by CyberManifest** [comment]
Thank You :-)
Kudos
