### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by DvrDania** [rajshekhar26/dotfiles#4]
Hi!
Amazing rice sir, I'm new to arch and I can't get this to work, can you help me please?
I don't know how to use packer, I installed it via AUR but PackerInstall is not available for me.
Trying to install tokyonight color scheme

**Comment by rjshkhr** [comment]
Open `~/.config/nvim/lua/setttings` and comment out `cmd [[colorscheme tokyonight]]` then PackerInstall will be available, run `PackerCompile` after `PackerInstall`. I have also updated the repo, you can pull it if you want.

**Comment by DvrDania** [comment]
> Open `~/.config/nvim/lua/setttings` and comment out `cmd [[colorscheme tokyonight]]` then PackerInstall will be available, run `PackerCompile` after `PackerInstall`. I have also updated the repo, you can pull it if you want.

It worked! Thanks

I also don't get battery and speaker icons in polybar top right, but I get the screen darkness icon, what font am I missing?

I installed Iosevka, ttf-nerd-fonts-symbols and JetBrains mono

**Comment by rjshkhr** [comment]
> I also don't get battery and speaker icons in polybar top right, but I get the screen darkness icon, what font am I missing?
> 
> I installed Iosevka, ttf-nerd-fonts-symbols and JetBrains mono

Iosevka and nerd font symbols that is mentioned in the README are the only ones needed for polybar. You can try changing the [icons](https://www.nerdfonts.com/cheat-sheet).

**Comment by DvrDania** [comment]
Sorry I decided to stick with learning these configuration myself from scratch 😉
