### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by ghost** [rajshekhar26/dotfiles#5]
First of all, hello! I saw your post on /r/webdev and found this repo while browsing your profile.
I see you like Arch and bspwm and, while I did find your post here https://www.reddit.com/r/unixporn/comments/p6tyf4/bspwm_us_and_them/ I see a lack of screenshots in the readme. 

Any plans to add those? If not, I can always do that for you (I'm new to github and I'd like the practice).

Oh and, I'm getting these dotfiles, it looks beautiful. Thanks!

**Comment by rajshekhar26** [comment]
@thanosades thanks for pointing it out, I didn't include screenshots because I change my setup frequently. But I think its a good a idea to add them, so I'll upload them on Imgur and then add the links in README.
